version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    container_name: Especialidad_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Especialidad_db


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      container_name: pgadmin4
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  pgdata:


# Run the following command to start the services
# docker-compose up -d